time: 2017-10-30 15:47:27.402044Z
tags: worker-2
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim
time: 2017-10-30 15:47:27.426043Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim [ multipart
]
tags: -worker-2
time: 2017-10-30 15:47:27.456923Z
tags: worker-1
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_register_k8sclient
time: 2017-10-30 15:47:27.480292Z
failure: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_register_k8sclient [ multipart
Content-Type: text/x-traceback;language=python,charset=utf8
traceback
24B
Traceback (most recent call last):
  File "tacker/tests/unit/nfvo/drivers/vim/test_kubernetes_driver.py", line 93, in test_register_k8sclient
    self._test_register_vim(self.vim_obj, mock_ks_client)
  File "tacker/tests/unit/nfvo/drivers/vim/test_kubernetes_driver.py", line 109, in _test_register_vim
    mock_fernet_obj.encrypt.assert_called_once_with(mock.ANY)
  File "/opt/stack/tacker/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 947, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'encrypt' to be called once. Called 2 times.
0
]
tags: -worker-1
time: 2017-10-30 15:47:27.518914Z
tags: worker-3
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim_barbican
time: 2017-10-30 15:47:27.536436Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim_barbican [ multipart
]
tags: -worker-3
time: 2017-10-30 15:47:27.521072Z
tags: worker-0
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_encode_vim_auth_barbican
time: 2017-10-30 15:47:27.541300Z
failure: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_encode_vim_auth_barbican [ multipart
Content-Type: text/x-traceback;language=python,charset=utf8
traceback
1B1
Traceback (most recent call last):
  File "tacker/tests/unit/nfvo/drivers/vim/test_kubernetes_driver.py", line 141, in test_encode_vim_auth_barbican
    mock_fernet_obj.encrypt.assert_called_once_with(mock.ANY)
  File "/opt/stack/tacker/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 947, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'encrypt' to be called once. Called 2 times.
0
]
tags: -worker-0
