time: 2017-10-30 16:39:35.943943Z
tags: worker-1
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim_barbican
time: 2017-10-30 16:39:35.961149Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim_barbican [ multipart
]
tags: -worker-1
time: 2017-10-30 16:39:36.079168Z
tags: worker-2
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_encode_vim_auth_barbican
time: 2017-10-30 16:39:36.095994Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_encode_vim_auth_barbican [ multipart
]
tags: -worker-2
time: 2017-10-30 16:39:36.114145Z
tags: worker-0
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_register_k8sclient
time: 2017-10-30 16:39:36.132046Z
failure: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_register_k8sclient [ multipart
Content-Type: text/x-traceback;charset=utf8,language=python
traceback
11F
Traceback (most recent call last):
  File "tacker/tests/unit/nfvo/drivers/vim/test_kubernetes_driver.py", line 94, in test_register_k8sclient
    self.keystone.initialize_client.assert_called_once_with(auth_obj)
AttributeError: 'TestKubernetes_Driver' object has no attribute 'keystone'
0
]
tags: -worker-0
time: 2017-10-30 16:39:36.114207Z
tags: worker-3
test: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim
time: 2017-10-30 16:39:36.136694Z
successful: tacker.tests.unit.nfvo.drivers.vim.test_kubernetes_driver.TestKubernetes_Driver.test_deregister_vim [ multipart
]
tags: -worker-3
